spring.application.name=backend

# Mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

# Postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# Kakao
kakao.client-id=${KAKAO_REST_API_KEY}
kakao.redirect-uri=${KAKAO_REDIRECT_URL}

# JWT
jwt.secret=${JWT_SECRET_KEY}
jwt.access-minutes=30
jwt.refresh-days=14

#mybatis
mybatis.type-handlers-package=com.example.backend.global.mybatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:mapper/*.xml

# redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.web.client.RestTemplate=TRACE

email.id=${EMAIL_ID}
email.password=${EMAIL_PASSWORD}

youtube.api=${YT_API_KEY}